# Generated by Django 4.0.6 on 2022-08-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('sex', models.CharField(db_column='sex', max_length=5)),
                ('birth', models.DateField(db_column='birth')),
            ],
        ),
    ]
