# Generated by Django 4.0.6 on 2022-08-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastingNote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemeta',
            name='date',
            field=models.DateTimeField(db_column='datetime'),
        ),
    ]
