# Generated by Django 4.0.6 on 2022-08-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='datetime')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('content', models.CharField(db_column='content', max_length=1000)),
            ],
        ),
    ]
